# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.cache/wt [current_project]
set_property parent.project_path C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/xilinx.com_user_data_memory_1.0
  c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/xilinx.com_user_instruction_memory_1.0
} [current_project]
set_property ip_output_repo c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram/insram0 .coe}}
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram/insram1.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram/insram2.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram/insram3.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram/dataram0.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram/dataram1.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram/dataram2.coe
add_files c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram/dataram3.coe
read_verilog -library xil_defaultlib {
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/ALU.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/CP0.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/HILOreg.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/LED.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/Mem_or_IO.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/access_datamemory.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/calculate_PC.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/data_memory.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/decode.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/decode_instruction.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/ex_mem.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/execute_instruction.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/extend.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/fetch_instruction.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/id_ex.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/if_id.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/instruction_memory.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/mem_wb.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/pc_add.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/pc_mux.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/pipedevices.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/post_data_memory.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/pre_data_memory.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/registers.v
  C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/new/Minisys_1A_CPU.v
}
read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram2/insram2.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram2/insram2_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram3/insram3.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram3/insram3_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram0/dataram0.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram0/dataram0_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram1/dataram1.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram1/dataram1_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram2/dataram2.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram2/dataram2_ooc.xdc]

read_ip -quiet c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram3/dataram3.xci
set_property used_in_implementation false [get_files -all c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/dataram3/dataram3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/constrs_1/new/TEST.xdc
set_property used_in_implementation false [get_files C:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/constrs_1/new/TEST.xdc]


synth_design -top Minisys_1A_CPU -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Minisys_1A_CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Minisys_1A_CPU_utilization_synth.rpt -pb Minisys_1A_CPU_utilization_synth.pb"
