# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0.xci
# IP: The module: 'insram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insram0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0.xci
# IP: The module: 'insram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram0/insram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insram0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
