# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1.xci
# IP: The module: 'insram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insram1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1.xci
# IP: The module: 'insram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIPSfpga/Minisys_1A_CPU/Minisys_1A_CPU/Minisys_1A_CPU.srcs/sources_1/ip/insram1/insram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insram1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
