# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yuanyuan/Ex_1/Ex_1.cache/wt [current_project]
set_property parent.project_path C:/Users/yuanyuan/Ex_1/Ex_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/sysclassfiles/interface/interface/Ex_1/S86_ip [current_project]
set_property ip_output_repo c:/Users/yuanyuan/Ex_1/Ex_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/sysclassfiles/interface/interface/Ex_1/rtl_up/initfile/init.coe
read_verilog -library xil_defaultlib {
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/reset.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/ACKgenerator.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/Decoder.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/Led.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/Muxdati.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/Switch.v
  C:/sysclassfiles/interface/interface/Ex_1/rtl_up/WRgenerator.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/digitron.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/PWM.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/Keyboard.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/timer.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/Dog.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/MemorIo.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/pipedevices.v
  C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/new/Segment_Clock.v
}
read_ip -quiet C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/S86_0/S86_0.xci

read_ip -quiet C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/uart_bmpg_16bit_0/uart_bmpg_16bit_0.xci

read_ip -quiet C:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all c:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yuanyuan/Ex_1/Ex_1.srcs/sources_1/ip/pll/pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/sysclassfiles/interface/interface/Ex_1/rtl_up/xdc/S86.xdc
set_property used_in_implementation false [get_files C:/sysclassfiles/interface/interface/Ex_1/rtl_up/xdc/S86.xdc]


synth_design -top S86SoC -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef S86SoC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file S86SoC_utilization_synth.rpt -pb S86SoC_utilization_synth.pb"
